title: "Salif Mehmed"
email: "salif@programmer.net"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://salifm.com"
markdown: kramdown
exclude:
  - run
  - README.md
  - LICENSE
include:
  - .well-known
